site_name: Jogo Digital - Grupo 1
site_url: https://github.com/UnBArqDsw2025-2-Turma01/2025.2-T01-G1_JogoDigital_Entrega_01

repo_url: https://github.com/UnBArqDsw2025-2-Turma01/2025.2-T01-G1_JogoDigital_Entrega_01
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UnBArqDsw2025-2-Turma01/2025.2-T01-G1_JogoDigital_Entrega_01

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep purple    
      accent: pink        
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top

nav:
  - Apresentação: index.md
  # - Entrega 1: 
  #   - Artefatos Generalistas: 
  #       - Entrega1/Artefatos Generalistas
  # - Planejamento: 
  #   - Cronograma: Planejamento/Cronograma/Cronograma.md
  #   - Ferramentas: Planejamento/Ferramentas/Ferramentas.md
  #   - Metodologia: Planejamento/Metodologia/Metodologia.md
  # - Reuniões:
  - 1. Desenho de Software: 
    - 1.1. Design Sprint: Base/1.1.DesignSprint.md
    - 1.2. Artefato Generalista:
          - Base: Base/1.2.ArtefatoGeneralista.md
    - 1.3. Modelagem BPMN: Base/1.3.ModelagemBPMN.md
    - 1.4. Participações - Base: Base/1.4.ParticipacoesBase.md
    - 1.5. Iniciativas Extras - Base: Base/1.5.IniciativasExtras.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
